# fly.toml app configuration file generated for discord-help-bot on 2023-06-25T03:43:33+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-help-bot"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
